# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0003_auto_20180618_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspiNombres', models.CharField(max_length=50)),
                ('aspiApellidos', models.CharField(max_length=50)),
                ('aspiGenero', models.CharField(max_length=1)),
                ('aspiNacimiento', models.DateField()),
                ('aspiCorreo', models.EmailField(max_length=60)),
                ('aspiDui', models.CharField(max_length=9)),
                ('aspiPasaporte', models.CharField(max_length=20)),
                ('aspiNit', models.CharField(max_length=14)),
                ('aspiNup', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('aspiTelefono', models.CharField(max_length=8)),
                ('aspiPaso', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Municipio')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('institucion', models.CharField(max_length=35)),
                ('tel_institucion', models.CharField(max_length=9)),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Conoc_Academico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=35)),
                ('codigo', models.CharField(max_length=10)),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Exp_Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('nombre_contacto', models.CharField(max_length=50, null=True)),
                ('correo_contacto', models.EmailField(max_length=60, null=True)),
                ('telefono_contacto', models.CharField(max_length=9)),
                ('anios_experiencia', models.IntegerField(null=True)),
                ('meses_experiencia', models.IntegerField(null=True)),
                ('area_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Area_Trabajo')),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
                ('puesto_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad_Tecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=9)),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
    ]
