# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_laboral',
            name='nombre_contacto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exp_laboral',
            name='nombre_empresa',
            field=models.CharField(max_length=50),
        ),
    ]
