# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='aspiPaso',
            field=models.IntegerField(default=1),
        ),
    ]
