# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0002_aspirante'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='aspirante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='numero_casa',
            field=models.IntegerField(),
        ),
    ]
