# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0002_auto_20180619_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp_laboral',
            old_name='telefono_empresa',
            new_name='telefono_contacto',
        ),
        migrations.AddField(
            model_name='exp_laboral',
            name='anios_experiencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exp_laboral',
            name='correo_contacto',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='exp_laboral',
            name='meses_experiencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
