# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0003_auto_20180602_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exp_Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('funcion', models.CharField(max_length=60)),
                ('telefono_empresa', models.CharField(max_length=9)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('aspirante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aspirante.Aspirante')),
            ],
        ),
    ]
