# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20180618_0614'),
        ('aspirante', '0004_auto_20180619_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp_laboral',
            name='area_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Area_Trabajo'),
        ),
        migrations.AddField(
            model_name='exp_laboral',
            name='puesto_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.Puesto'),
        ),
    ]
